image: jangrewe/gitlab-ci-android

stages:
  - deploy

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

deploy:
  script:
    - 'gradle publish'
  only:
    - main