name: publish-library
run-name: Publish library
on:
    push:
        branches:
        - main
jobs:
    publish:
        name: Publish library
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'temurin'
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Publish library
          run: ./gradlew publish
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}